version: '3.8'

services: 
  master1:
    build:
      context: .
      dockerfile: ./master1/DOCKERFILE
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: test
    container_name: mhr_master1
    volumes:
      - ./master1/mysqlconf:/etc/mysql/conf.d
      - ./master1/data:/var/lib/mysql
      - ./master1/sql-scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 5001:3306


  hybrid1:
    build:
      context: .
      dockerfile: ./hybrid1/DOCKERFILE
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: test
    container_name: mhr_hybrid1
    volumes:
      - ./hybrid1/mysqlconf:/etc/mysql/conf.d
      - ./hybrid1/data:/var/lib/mysql
      - ./hybrid1/sql-scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 5002:3306

  repl1:
    build:
      context: .
      dockerfile: ./repl1/DOCKERFILE
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234567890
      MYSQL_DATABASE: test
    container_name: mhr_repl1
    volumes:
      - ./repl1/mysqlconf:/etc/mysql/conf.d
      - ./repl1/data:/var/lib/mysql
      - ./repl1/sql-scripts/:/docker-entrypoint-initdb.d/
    ports:
      - 5003:3306
